#10 List Entries-Toggl
kommitters/toggltick-js pull request #27
Opened 2021-10-26 21:53 UTC by MarioRodriguezS

Fix #10 

## Description
The project structure was created as well as the module to get the entries from the Toggl API using a start_date and an end_date parameters, these use the iso8601 date format. The api_token is stored in a .env file.

2021-10-29 18:04 UTC, brayvasq requested changes

2021-10-29 18:04 UTC, brayvasq commented on src/clients/toggl/entries/list.js
> +export default getTogglEntries;
@MarioRodriguezS What if we export it in the following way?
```javascript
export default { getTogglEntries }
```

It'd be useful when we add more functions to this file.

2021-10-29 18:04 UTC, brayvasq commented on test/clients/toggl/list.test.js
> +import { togglGetEntriesError, togglGetEntriesResponse } from '../../fixture/clients/toggl/listResponse.js';
@MarioRodriguezS this should be imported without the relative path, right?

2021-10-29 18:14 UTC, brayvasq requested changes

2021-10-29 18:14 UTC, brayvasq commented on src/clients/toggl/entries/list.js
> +import { TOGGL_API_TOKEN, TOGGL_BASE_URL } from 'toggltick-js/config';
@MarioRodriguezS this should be just `... from 'config';` right?

2021-10-29 18:14 UTC, brayvasq commented on test/clients/toggl/list.test.js
> +import getTogglEntries from 'toggltick-js/src/clients/toggl/entries/list';
@MarioRodriguezS this should be just `... from 'src/clients/toggl/entries/list';` right?

2021-10-29 18:20 UTC, MarioRodriguezS commented on test/clients/toggl/list.test.js
> +import getTogglEntries from 'toggltick-js/src/clients/toggl/entries/list';
No, if you set a subpath export in the package.json, when you use it inside the import, you have to use the name of the project follows by the custom path. ...from 'toggltick-js/src/....'.

https://nodejs.org/api/packages.html#subpath-exports

2021-10-29 19:53 UTC, JoseCastroA commented on test/clients/toggl/list.test.js
> +import getTogglEntries from 'toggltick-js/src/clients/toggl/entries/list';
@MarioRodriguezS Do you want to check if we can edit the subpath-export? To avoid using the project name in the path. If not, we should look for other options.

2021-11-01 18:09 UTC, brayvasq approved these changes

2021-11-01 21:14 UTC, merged