create and test the create toggl entry module
kommitters/toggltick-js pull request #28
Opened 2021-11-01 22:59 UTC by MarioRodriguezS

## Description
The create toggl entries module was implemented with the respective tests, the post request needs a data entry object specified in the documentation: 

https://github.com/toggl/toggl_api_docs/blob/master/chapters/time_entries.md#time-entries 

fix #11

2021-11-02 21:45 UTC, brayvasq approved these changes

2021-11-02 21:45 UTC, brayvasq commented on src/clients/toggl/entries/create.js
> +const createTogglEntries = async (dataEntry) => {
@MarioRodriguezS @JoseCastroA Do you think we need to document it or specify the items of `dataEntry` object?

2021-11-02 21:45 UTC, brayvasq commented on test/clients/toggl/create.test.js
> +  describe('when API call is not succesful', () => {
@MarioRodriguezS Did you test when the data is incorrect or a field is missing?

2021-11-02 21:45 UTC, brayvasq commented on test/fixture/clients/toggl/createResponse.js
> +export const togglCreateEntriesResponse = {
@MarioRodriguezS @JoseCastroA Does this file have common elements with other fixtures? What if we create some kind of factories to replace only the necessary data?

What do you think?

2021-11-02 22:14 UTC, MarioRodriguezS commented on src/clients/toggl/entries/create.js
> +const createTogglEntries = async (dataEntry) => {
I think that we could document the method, it is a good idea.

2021-11-02 22:14 UTC, MarioRodriguezS commented on test/fixture/clients/toggl/createResponse.js
> +export const togglCreateEntriesResponse = {
Sure!

2021-11-04 14:10 UTC, brayvasq requested changes

2021-11-04 14:10 UTC, brayvasq commented on test/fixture/clients/toggl/dataEntryCreateEntry.js
> +  created_with: 'toggltickjs',
@MarioRodriguezS why does this object have almost the same data as `dataEntryCreate`?

what if we do something like this in the test:` Should reject with an error when required data missed`
```
const {duration, ...dataEntry} = dataEntryCreate;
```
Also, we could rename the `dataEntryCreate` object as` dataEntry`.

2021-11-04 14:10 UTC, brayvasq commented on test/clients/toggl/create.test.js
> +import { togglCreateEntriesError, togglCreateEntriesResponse, toogglCreateEntriesMissedData } from '#test/fixture/clients/toggl/createResponse';
@MarioRodriguezS This line is too long. Please format it.

2021-11-04 14:10 UTC, brayvasq commented on test/fixture/clients/toggl/createResponse.js
> +// console.log(toogglCreateEntriesMissedData);
@MarioRodriguezS Please do not add `console.log` lines, at least strictly necessary. Be carefull with that.

2021-11-05 16:35 UTC, brayvasq requested changes

2021-11-05 16:35 UTC, brayvasq commented on test/clients/toggl/create.test.js
> +  from '#test/fixture/clients/toggl/createResponse';
@MarioRodriguezS this line is too long. We should organize this import as following:
```javascript
import {
  importItem1,
  importItem2,
  .....
} from '.....';
```

2021-11-05 16:35 UTC, brayvasq commented on test/fixture/clients/toggl/createResponse.js
> +const toogglCreateEntriesMissedData = { response: responseGenerator(400, 'Bad Request', 'post', dataEntryMissed, messageTimeMissed, auth) };
@MarioRodriguezS This line is also too long. What if we do the following?:
```javascript
const toogglCreateEntriesMissedData = { 
    response: responseGenerator(400, 'Bad Request', 'post', dataEntryMissed, messageTimeMissed, auth) 
};
```

2021-11-05 16:35 UTC, brayvasq commented on test/fixture/clients/toggl/responseGenerator.js
> +  dataResponse, authorization) => ({
@MarioRodriguezS if the line is too long, What if weorganize the params like this?:
```javascript
const responseGenerator = (
 param1,
 param2,
 .....
) => .....
```

2021-11-05 18:20 UTC, brayvasq requested changes

2021-11-05 18:20 UTC, brayvasq commented on test/clients/toggl/list.test.js
> +  from '#test/fixture/clients/toggl/listResponse';
@MarioRodriguezS If this line does not meet the length restriction, I think it would be clearer if we write it like this:
```javascript
import { 
  togglGetEntriesError,
  togglGetEntriesResponse 
}  from '#test/fixture/clients/toggl/listResponse';
```

2021-11-05 18:29 UTC, brayvasq approved these changes

2021-11-05 18:30 UTC, merged